# Shared non-secret data for chezmoi templates

default_hostname = "void(0)"
tree_ignore = ".git|node_modules"
dock_apps = ["Zen", "Notion", "Visual Studio Code", "Microsoft Teams", "Discord", "GitKraken"]
