tap "buo/cask-upgrade"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "hpedrorodrigues/tools"
tap "ubuntu/microk8s"
brew "python@3.11"
brew "azure-cli"
brew "bash"
brew "cloudflared"
brew "colima"
brew "cowsay"
brew "curl"
brew "dockutil"
brew "emacs"
brew "node"
brew "eslint"
brew "ffmpeg"
brew "gh"
brew "git"
brew "github-keygen"
brew "gnupg"
brew "grep"
brew "helm"
brew "jq"
brew "k9s"
brew "lolcat"
brew "mackup"
brew "mariadb"
brew "mas"
brew "minikube"
brew "nvm"
brew "opa"
brew "openjdk"
brew "pinentry-mac"
brew "poetry"
brew "postgresql@14"
brew "prettier"
brew "putty"
brew "redis"
brew "snyk-cli"
brew "speedtest-cli"
brew "stow"
brew "swagger-codegen"
brew "telnet"
brew "vite"
brew "wget"
brew "yt-dlp"
brew "zsh"
cask "adobe-acrobat-reader", args: { appdir: "/Applications" }
cask "aldente", args: { appdir: "/Applications" }
cask "android-studio", args: { appdir: "/Applications" }
cask "arc", args: { appdir: "/Applications" }
cask "autodesk-fusion360", args: { appdir: "/Applications" }
cask "bartender", args: { appdir: "/Applications" }
cask "blender", args: { appdir: "/Applications" }
cask "bricklink-studio", args: { appdir: "/Applications" }
cask "citrix-workspace", args: { appdir: "/Applications" }
cask "desmume", args: { appdir: "/Applications" }
cask "discord", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "dockutil"
cask "dolphin", args: { appdir: "/Applications" }
cask "fig", args: { appdir: "/Applications" }
cask "figma", args: { appdir: "/Applications" }
cask "focusrite-control-2", args: { appdir: "/Applications" }
cask "github", args: { appdir: "/Applications" }
cask "gitkraken", args: { appdir: "/Applications" }
cask "google-chrome", args: { appdir: "/Applications" }
cask "httpie", args: { appdir: "/Applications" }
cask "intellij-idea", args: { appdir: "/Applications" }
cask "intune-company-portal", args: { appdir: "/Applications" }
cask "jetbrains-toolbox", args: { appdir: "/Applications" }
cask "keyboardcleantool", args: { appdir: "/Applications" }
cask "logi-options-plus", args: { appdir: "/Applications" }
cask "microsoft-auto-update"
cask "microsoft-teams", args: { appdir: "/Applications" }
cask "minecraft", args: { appdir: "/Applications" }
cask "miro", args: { appdir: "/Applications" }
cask "mongodb-compass", args: { appdir: "/Applications" }
cask "nordvpn", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "obs", args: { appdir: "/Applications" }
cask "openemu", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "raycast", args: { appdir: "/Applications" }
cask "sf-symbols", args: { appdir: "/Applications" }
cask "soundsource", args: { appdir: "/Applications" }
cask "steam", args: { appdir: "/Applications" }
cask "tableplus", args: { appdir: "/Applications" }
cask "tg-pro", args: { appdir: "/Applications" }
cask "unity-hub", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "vivid", args: { appdir: "/Applications" }
vscode "aaron-bond.better-comments"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.Bookmarks"
vscode "alefragnani.project-manager"
vscode "alexcvzz.vscode-sqlite"
vscode "austenc.tailwind-docs"
vscode "axmmisaka.felonious-cpp-formatter"
vscode "benjaminbenais.copilot-theme"
vscode "bierner.markdown-preview-github-styles"
vscode "bourhaouta.tailwindshades"
vscode "bradlc.vscode-tailwindcss"
vscode "castwide.solargraph"
vscode "ChakrounAnas.turbo-console-log"
vscode "ChaunceyKiwi.json-tree-view"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codeandstuff.package-json-upgrade"
vscode "codezombiech.gitignore"
vscode "csholmq.excel-to-markdown-table"
vscode "CTC.vscode-tree-extension"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-redis-client"
vscode "dalirnet.mongod-config"
vscode "dariofuzinato.vue-peek"
vscode "DavidAnson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "dgileadi.java-decompiler"
vscode "DotJoshJohnson.xml"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "Fatih.baba-flow"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "foxundermoon.shell-format"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.github-vscode-theme"
vscode "GitHub.heygithub"
vscode "GitHub.remotehub"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "Gruntfuggly.todo-tree"
vscode "hediet.vscode-drawio"
vscode "hnw.vscode-auto-open-markdown-preview"
vscode "hollowtree.vue-snippets"
vscode "humao.rest-client"
vscode "hurly.sqltools-oracle-driver"
vscode "ipedrazas.kubernetes-snippets"
vscode "IronGeek.vscode-env"
vscode "jakeboone02.cypher-query-language"
vscode "janisdd.vscode-edit-csv"
vscode "JannisX11.batch-rename-extension"
vscode "JFrog.jfrog-vscode-extension"
vscode "jianbingfang.dupchecker"
vscode "jnbt.vscode-rufo"
vscode "jock.svg"
vscode "kamikillerto.vscode-colorize"
vscode "KevinRose.vsc-python-indent"
vscode "kodezi.kodezi"
vscode "leizongmin.node-module-intellisense"
vscode "lunuan.kubernetes-templates"
vscode "mechatroner.rainbow-csv"
vscode "meganrogge.template-string-converter"
vscode "mgesbert.python-path"
vscode "mikestead.dotenv"
vscode "mindaro-dev.file-downloader"
vscode "mindaro.mindaro"
vscode "MisterJ.vue-volar-extention-pack"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "MS-CEINTL.vscode-language-pack-de"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-python.autopep8"
vscode "ms-python.black-formatter"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.brackets-keybindings"
vscode "ms-vscode.brackets-pack"
vscode "ms-vscode.js-atom-grammar"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "mtxr.sqltools"
vscode "mwpb.java-prettier-formatter"
vscode "mycelo.oracle-plsql"
vscode "njpwerner.autodocstring"
vscode "oderwat.indent-rainbow"
vscode "Oracle.oracledevtools"
vscode "PKief.material-icon-theme"
vscode "plex.vscode-regolint"
vscode "pranaygp.vscode-css-peek"
vscode "Prisma.prisma"
vscode "purocean.drawio-preview"
vscode "qwtel.sqlite-viewer"
vscode "rafamel.subtle-brackets"
vscode "RandomFractalsInc.vscode-data-preview"
vscode "rangav.vscode-thunder-client"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-microprofile"
vscode "redhat.vscode-openshift-connector"
vscode "redhat.vscode-quarkus"
vscode "redhat.vscode-redhat-account"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.LiveServer"
vscode "roerohan.mongo-snippets-for-node-js"
vscode "rogalmic.bash-debug"
vscode "rvest.vs-code-prettier-eslint"
vscode "SAPSE.vscode-cds"
vscode "sdras.vue-vscode-snippets"
vscode "sgryjp.vscode-stable-sort"
vscode "shakram02.bash-beautify"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "Shinotatwu-DS.file-tree-generator"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "SimonSiefke.svg-preview"
vscode "sketchbuch.vsc-quokka-statusbar"
vscode "snyk-security.snyk-vulnerability-scanner"
vscode "stackbreak.comment-divider"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-german"
vscode "svelte.svelte-vscode"
vscode "syler.sass-indented"
vscode "tamasfe.even-better-toml"
vscode "testdouble.vscode-standard-ruby"
vscode "tomoki1207.pdf"
vscode "tsandall.opa"
vscode "unclebeast.har-viewer"
vscode "usernamehw.errorlens"
vscode "VirejDasani.incredibly-in-your-face"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vmware.vscode-spring-boot"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
vscode "vsls-contrib.codetour"
vscode "Vue.volar"
vscode "Vue.vscode-typescript-vue-plugin"
vscode "WallabyJs.console-ninja"
vscode "WallabyJs.quokka-vscode"
vscode "WallabyJs.wallaby-vscode"
vscode "wayou.vscode-icons-mac"
vscode "wekex.JsonLint"
vscode "xabikos.JavaScriptSnippets"
vscode "xaver.clang-format"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "zaaack.markdown-editor"
vscode "Zarifprogrammer.tailwind-snippets"
vscode "Zignd.html-css-class-completion"
vscode "znck.vue"
